# ----------------------------------------------------------------------------
# General Configuration
# ----------------------------------------------------------------------------

Game:
  Permissions:
    StartGame: advancementhunt.command.start
    SetLocation: advancementhunt.command.set
  MySQL:
    Host: localhost
    Port: '3306'
    Database: advancementhunt
    Options: ?autoReconnect=true
    User: root
    Password: passwd'
    table_prefix: ah_
    Use_db: false
  Extra:
    Hub_Server: Hub
    WorldName: advancementhunt
