version: 1 # Don't touch this! For future use.

# ----------------------------------------------------------------------------
# AdvancementHunt Main Configuration
# ----------------------------------------------------------------------------
db:
  type: sqlite # Can be either sqlite or mysql.
  prefix: ah_
  # SQLite only!
  filename: database.sqlite # Must be a relative path.
  # MySQL only!
  host: localhost
  port: 3306
  name: advancementhunt
  options: ?autoReconnect=true
  user: root
  passwd: ''
game:
  start_on_join: true # If the game should start when everybody has joined the server. (max amount of players)
  max_to_zero: true # If the server's max player count should be set to zero while a game is ongoing.
  startup: 5 # If a countdown should be displayed while a game is starting.
  before: 5 # How long the pre-countdown should last. Players will be unable to move.
  countdown: 10 # How long the countdown should last before the game starts. Players will be invulnerable, but be able to move.
  compass: true # Whether or not a compass will be granted to hunters that will point to the hunted.
matchmaker: # For the MatchmakerBukkit bridge. Requires the plugin to be installed.
  after_game: lobby # The game to be set to after a game is over.
  rampdown: 7 # How long to wait after the game is over to send people to the game.

# ----------------------------------------------------------------------------
# AdvancementHunt Messages
#
# You may use PlaceholderAPI placeholders in these messages. Use "&" for codes.
#
# Each key should hold an array.
#   Each item in the array should be an object.
#     The object should have the following keys:
#       send_type: This may be either title, actionbar, or chat.
#       message: The actual message to send.
#       submessage: Only applies if send_type is title.
# ----------------------------------------------------------------------------
kick_message: "A game of AdvancementHunt is currently ongoing! Please check back later." # This message will be shown to users if they attempt to connect while a game is ongoing.
messages:
  hunter_gamestart:
    - send_type: title
      message: "Go!"
      submessage: "Kill %ah_hunted%!"
  hunted_gamestart:
    - send_type: title
      message: "Go! Get %ah_advancement%!"
  hunter_persistent: # This will appear during the whole game and be refreshed every second.
    - send_type: actionbar
      message: "%ah_time% | %ah_hunted%"
  hunted_persistent: # This will appear during the whole game and bce refreshed every second.
    - send_type: actionbar
      message: "%ah_time% | %ah_advancement%"
  hunter_win:
    - send_type: title
      message: "%ah_hunters% have won!"
      submessage: "The game is over!"
  hunted_win:
    - send_type: title
      message: "%ah_hunted% has won!"
      submessage: "The game is over!"
  hunter_start:
    - send_type: title
      message: "Kill %ah_hunted%!"
      submessage: "Get going!"
  hunted_start:
    - send_type: title
      message: "Get the advancement %ah_advancement%!"
      submessage: "Avoid %ah_hunters%."
  time_up:
    - send_type: title
      message: "Time's up!"
      submessage: "Everybody loses!"
  left:
    - send_type: title
      message: "Someone left!"
      submessage: "Does this count as a stalemate?"
