name: Advancementhunt
version: ${project.version}
main: de.teddy.advancementhunt.AdvancementHunt
api-version: 1.13
author: regulad
depend: [PlaceholderAPI, Multiverse-Core, Multiverse-NetherPortals]

commands:
  set:
  gamestart:
  debug:
