name: Advancementhunt
version: 0.2.0
description: AdvancementHunt/Manhunt plugin for SquirrelNet
authors: [regulad, abhiram

main: de.teddy.advancementhunt.AdvancementHunt
depend: [PlaceholderAPI, Multiverse-Core, Multiverse-NetherPortals]
api-version: 1.15

commands:
  set:
  gamestart:
  debug:
