name: ${project.name}
version: ${project.version}
description: AdvancementHunt/Manhunt Plugin
author: regulad

main: com.regulad.advancementhunt.AdvancementHunt
softdepend: [Multiverse-NetherPortals]
depend: [PlaceholderAPI, Multiverse-Core]
api-version: 1.15

commands:
  set:
  gamestart:
  debug:
