name: Advancementhunt
version: 1.1-SNAPSHOT
description: AdvancementHunt/Manhunt plugin for SquirrelNet
authors: [regulad, abhiram]

main: de.teddy.advancementhunt.AdvancementHunt
depend: [PlaceholderAPI, Multiverse-Core]
api-version: 1.15

commands:
  set:
  gamestart:
  debug:
