name: AdvancementHunt
version: ${project.version}
description: AdvancementHunt is a minigame plugin.
author: regulad

main: quest.ender.AdvancementHunt.AdvancementHunt
depend:
  - PlaceholderAPI
  - Multiverse-Core
  - Multiverse-Inventories
  - Multiverse-NetherPortals
softdepend:
  - Matchmaker
api-version: 1.17
libraries:
  - org.jetbrains:annotations:21.0.1
  - org.javatuples:javatuples:1.2

permissions:
  advancementhunt.*:
    description: Grants all AdvancementHunt permissions.
    children:
      - advancementhunt.commands.*
  advancementhunt.commands.*:
    description: Grants access to all AdvancementHunt commands.
    children:
      - advancementhunt.commands.game.*
      - advancementhunt.commands.register.*
  advancementhunt.commands.game.*:
    description: Grants access to commands used for controlling the game.
    children:
      - advancementhunt.commands.game.start
      - advancementhunt.commands.game.end
  advancementhunt.commands.game.start:
    description: Grants access to /gamestart.
  advancementhunt.commands.game.end:
    description: Grants access to /gameend.
  advancementhunt.commands.register.*:
    description: Grants access to commands used to register advancements & word seeds.
    children:
      - advancementhunt.commands.register.advancement
      - advancementhunt.commands.register.seed
  advancementhunt.commands.register.advancement:
    description: Grants access to /registeradvancement.
  advancementhunt.commands.register.seed:
    description: Grants access to /registerseed.

commands:
  gamestart:
    permission: advancementhunt.commands.game.start
    description: Allows you to start the game.
    usage: "Usage: /<command> [Hunted player] [Advancement] <Time (Minutes)> [World seed] <Worldborder>"
  gameend:
    permission: advancement.commands.game.end
    description: Allows you to end the game.
    usage: "Usage: /<command>"
  registeradvancement:
    permission: advancementhunt.commands.register.advancement
    description: Allows you to add an advancement and time limit to the database.
    usage: "Usage: /<command> <Advancement> <Time (Minutes)>"
  registerseed:
    permission: advancementhunt.commands.register.seed
    description: Allows you to add a seed and worldborder size to the database.
    usage: "Usage: /<command> <World seed> <Worldborder>"
