name: Deploy package
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish:
    environment: regulad-releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up maven repository
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          distribution: adopt
          server-id: regulad-releases
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SERVER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
